version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências do node"
      - npm ci
  build:
    commands:
      - echo "Compilando TypeScript"
      - npm run build
      - echo "Criando .env"
      - |
        cat <<EOF > .env
        DATABASE_URL=postgres://boamassauser:admin@localhost:5432/boamassa

        # Secret JWT https://www.md5hashgenerator.com
        JWT_SECRET=3a3253a19ee38b154d26d036db1a4b52

        PORT=8080
        EOF
      - echo "Preparando diretório de deploy"
      - mkdir -p deploy
      - pwd
      - ls -la
      - cp -r Dockerfile docker-compose.yml prisma src package*.json .env .ebextensions deploy/ 
  post_build:
    commands:
      - echo "Gerado artefato"
artifacts:
  files:
    - deploy/
