version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Instalando dependências"
      - npm ci
  build:
    commands:
      - echo "Compilando TypeScript"
      - npm run build
      - echo "Preparando diretório de deploy"
      - mkdir -p deploy
      - cp -r Dockerfile package*.json dist prisma deploy/
  post_build:
    commands:
      - echo "Gerando artefato deploy.zip"
      - cd deploy && zip -r ../deploy.zip .
artifacts:
  files:
    - deploy.zip
