name: PR Auto para Develop

on:
  push:
    branches:
      - develop

jobs:
  auto_pr_to_master:
    if: startsWith(github.event.ref, 'refs/heads/') && github.event.sender.login != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Cria Pull Request para master
        uses: peter-evans/create-pull-request@v5
        with:
          source: ${{ github.ref_name }}
          target: master
          title: 'PR: ${{ github.ref_name }} → master'
          body: |
            PR automático criado a partir da branch `${{ github.ref_name }}` para `master`.
          branch: auto/${{ github.ref_name }}-to-master
