name: PR automático develop → master

on:
  push:
    branches:
      - develop

jobs:
  create-pr-to-master:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/github/gh-cli:latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Criar Pull Request para master
        run: |
          # Evita criar PR se já existir um aberto do develop para master
          gh pr list --base master --head develop --json number | grep -q '"number":' && echo "PR já existe" && exit 0

          gh pr create \
            --title "PR automático: develop → master" \
            --body "Merge automático de develop para master após alterações." \
            --base master \
            --head develop \
            --label "auto-pr"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
